server:
  port: 8762
  #    jsp热部署
  servlet:
    jsp:
      init-parameters:
        development: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka
spring:
  redis:
    host: 192.168.80.138
    port: 7070
    database: 0
    jedis:
      pool:
        max-wait: -1
        min-idle: 0
        max-active: 8
        max-idle: 8
  application:
    name: shop
  mvc:
    view:
      suffix: .jsp
      prefix: /
logging:
  level: 
    com.zq.dao: debug
ribbon:
  ReadTimeOut: 10000
  ConnectTimeout: 12000
